import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>舞瞳喵的機器人指令空間</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/55Hitomi.png" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h1 className={styles.title}>
          舞瞳喵的機器人指令空間
        </h1>

        <p className={styles.description}>
          這邊是給舞瞳喵的機器人讀取程式碼的空間。
        </p>

        <div className={styles.grid}>
          <a href="https://www.twitch.tv/sulen0820" className={styles.card}>
            <h2>舞瞳喵圖奇</h2>
            <p>舞瞳喵的圖奇實況連結。</p>
          </a>
          <a href="https://discord.com/invite/vSUT6YNbsp" className={styles.card}>
            <h2>舞瞳喵Discord</h2>
            <p>舞瞳喵的Discord連結。</p>
          </a>
        </div>
      </main>
    </>
  );
}
